/* Data Loading Operations */
// All data, barring the first playlist and its content, was generated by Metamate

// Request and load data
async function loadData() {
    try {
        // Gather playlist array
        const response = await fetch('./data/data.json');
        if (!response.ok) {
            throw new Error('Data retrieval: bad response');
        }
        const playlists = await response.json();

        // Establish cards
        let cardBase = document.getElementsByClassName("playlist-cards")[0];
        // Build playlist cards and their respective modals
        playlists.forEach(pl => {
            // Build card | Indentations represent divisional nestings
            let card = document.createElement("article");
                card.id = `card${pl.playlistID}`;

                // Card image
                let cardPlCover = document.createElement("img");
                    cardPlCover.id = 'cover';
                    cardPlCover.onclick = () => {
                        toggleModal(card.id);
                    }
                    cardPlCover.src = pl.playlist_art;
                    cardPlCover.alt =  'playlist cover';
                    card.appendChild(cardPlCover);

                // Playlist name
                let cardPlName = document.createElement("h2");
                    cardPlName.textContent = pl.playlist_name;
                    card.appendChild(cardPlName);

                // Playlist author
                let cardPlAuthor = document.createElement("p");
                    cardPlAuthor.textContent = `by ${pl.playlist_author}`;
                    card.appendChild(cardPlAuthor);
                
                // Like counter division
                let lcDiv = document.createElement("div");
                    lcDiv.className = 'likecount';
                    let heart = document.createElement("img");
                        heart.id = `heart${pl.playlistID}`;
                        heart.className = "empty";
                        heart.onclick = () => {
                            likePL(heart.id);
                        }
                        heart.src = './assets/img/hearticon.png';
                        heart.alt = 'a heart icon';
                        lcDiv.appendChild(heart);
                    let likecount = document.createElement("p");
                        likecount.textContent = pl.like_count;
                        lcDiv.appendChild(likecount);
                    card.appendChild(lcDiv);
                
            cardBase.appendChild(card);

            // Establish modals list
            let modalsBase = document.getElementsByClassName("playlist-modals")[0];
                // Build modal and its respective songs list
                // Indentations represent divisional nestings
                let modal = document.createElement("div");
                    modal.className = `modalContent${pl.playlistID}`;
                    
                    // Playlist header
                    let header = document.createElement("div");
                        header.className = "playlistHeader";
                        
                        // Left side: Cover and general info
                        let hLeft = document.createElement("div");
                            hLeft.className = "left";
                            let modPlCover = document.createElement("img");
                            modPlCover.id = 'cover';
                            modPlCover.src = pl.playlist_art;
                            modPlCover.alt =  'playlist cover';

                            // Cover
                            hLeft.appendChild(modPlCover);

                            // Gen. info
                            let plInfo = document.createElement("div");
                                plInfo.className = "plInfo";
                                let plName = document.createElement("h3");
                                    plName.textContent = pl.playlist_name;
                                    plInfo.appendChild(plName);
                                let plAuthor = document.createElement("p");
                                    plAuthor.textContent = `by ${pl.playlist_author}`;
                                    plInfo.appendChild(plAuthor);
                                hLeft.appendChild(plInfo);
                            header.appendChild(hLeft);
                        
                        // Right side: X icon to exit
                        let xicon = document.createElement("img");
                            xicon.id = "xicon";
                            xicon.className = "close";
                            xicon.onclick = toggleModal;
                            xicon.src = './assets/img/xicon.svg';
                            header.appendChild(xicon);
                        
                        modal.appendChild(header);
                    
                    // Playlist content: list of songs
                    let plContent = document.createElement("div");
                        plContent.className = `playlistContent${pl.playlistID}`;

                        pl.songs.forEach(song => {
                            let songItem = document.createElement("article");

                                // Left side of song item: cover, gen. info
                                let sLeft = document.createElement("div");
                                    sLeft.className = "left";

                                    // Cover
                                    let sCover = document.createElement("img");
                                        sCover.id = "cover";
                                        sCover.src = song.cover;
                                        sCover.alt = "song cover";
                                        sLeft.appendChild(sCover);
                                    
                                    // Gen. info
                                    let sInfo = document.createElement("div");
                                        sInfo.className = "songInfo";
                                        let sTitle = document.createElement("h3");
                                            sTitle.innerText = song.title
                                            sInfo.appendChild(sTitle);
                                        let artist = document.createElement("p");
                                            artist.innerText = song.artist;
                                            sInfo.appendChild(artist);
                                        let album = document.createElement("p");
                                            album.innerText = song.album;
                                            sInfo.append(album);
                                        sLeft.appendChild(sInfo);
                                    songItem.appendChild(sLeft);
                                
                                // Right side of song item: runtime
                                let sRight = document.createElement("div");
                                    sRight.className = "right";
                                    let runtime = document.createElement("p");
                                        runtime.innerText = song.runtime;
                                        sRight.appendChild(runtime);
                                    songItem.appendChild(sRight);
                                    
                            plContent.appendChild(songItem);
                        });
                        modal.appendChild(plContent);
                modalsBase.appendChild(modal);
        });

    } catch (error) {
        console.error('Data retrieval: ', error);
    }
}
loadData();

/* Modal Open/Close Operations */
function toggleModal(id) {
    // Unhide the modal overlay. If already open, reset statuses and exit
    let modal = document.getElementsByClassName("playlist-modals")[0];
    if (modal.style.display === "flex") {
        modal.style.display = "none";
        let pl = document.getElementsByClassName(`modalContent${modal.id}`)[0];
        pl.style.display = "none";
        modal.setAttribute("id", null);
        return;
    }
    modal.style.display = "flex";
    
    // Unhide only the specfic modal requested
    let idNum = id.split("card")[1];
    let pl = document.getElementsByClassName(`modalContent${idNum}`)[0];
    pl.style.display = "block";

    // Give the modal overlay a modal id to check when resetting statuses later
    modal.setAttribute("id", idNum);

}
window.onclick = function(event) {
    // Resets status and exits modal overlay when surrounding area is clicked
    if (event.target.className === "playlist-modals") {
        event.target.style.display = "none";
        let pl = document.getElementsByClassName(`modalContent${event.target.id}`)[0];
        pl.style.display = "none";
        event.target.setAttribute("id", null);
    }
}

/* Liking Operations */
async function likePL(id) {
    try {
        // Gather playlist array
        const response = await fetch('./data/data.json');
        if (!response.ok) {
            throw new Error('Data retrieval: bad response');
        }
        const playlists = await response.json();

        let curHeart = document.getElementById(id);
        if (curHeart.className === "empty") {
            curHeart.setAttribute("src", './assets/img/fullheart.png');
            curHeart.setAttribute("class", "full");
            playlists[id.split("heart")[1]].like_count += 1;
            console.log(playlists[id.split("heart")[1]].like_count);
        }
        else {
            curHeart.setAttribute("src", './assets/img/hearticon.png');
            curHeart.setAttribute("class", "empty");
            playlists[id.split("heart")[1]].like_count -= 1;
            console.log(playlists[id.split("heart")[1]].like_count);
        }
    } catch (error) {
        console.error('Liking: ', error);
    }
}